export { default as NavBar } from './navbar/navbar'
export { default as Home } from './home/home'
export { default as AboutUs } from './about-us/about-us'
export { default as Contact } from './contact/contact'
export { default as SpecialMenu } from './special-menu/special-menu'